import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import me from "../public/me.png";
import zen from "../public/zen.png";
import icon from "../public/icon.png";
import firebaseIcon from "../public/firebaseIcon.png";
import payment from "../public/payment.png";
import ReactPlayer from "../public/ReactPlayer.png";
import Phanox from "../public/Phanox.png";
import Kicks from "../public/Kicks.png";
import VideoApp from "../public/VideoApp.png";
import Realtor from '../public/Realtor.png';
import UniswapClone from "../public/UniswapClone.png";
import LeviResume from "../public/LeviResume.png";
import {useState} from "react";




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
 
    
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title className="dark:text-white">programmingWithLevi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-white">programmingWithLevi</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl dark:text-white" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="LeviResume.png" download="LeviResume.png"
                  
                >
                  
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Levi Chambers
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Web Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              
              Freelance front-end developer seeking a full-time position. 
            </p>
            
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.facebook.com/profile.php?id=100008649966877" target="_blank" rel="noreferrer">
            <AiFillFacebook className="cursor-pointer"/>
            </a>
            <a
              href="https://www.linkedin.com/in/levi-chambers-073079122/" target="_blank" rel="noreferrer">
            <AiFillLinkedin />
            </a>
            <a
              href="https://www.instagram.com/programmingwithlevi/" target="_blank" rel="noreferrer">
            <AiFillInstagram />
            </a>
            
          </div>
          <div className=" relative  mx-auto w-80 h-80 mt-20 md:h-96 md:w-96">
            <Image src={me} className="rounded-full margin mt-20" alt=""/>
          </div>
        </section>
        <section className="items-center">
          <div className="p-10 leading-8">
            <h3 className="text-3xl py-1 mt-20 dark:text-white">Services I offer:</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              I specialize in front-end interfaces and full-stack web apps for
              product advertising, ecommerce, and media. These apps are rendered on the server, 
              making them lightweight, quick, and SEO friendly.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              Unlike a Wordpress, Shopify, or Wix, my products are ready to scale
              as a business expands. My customers are never locked into any platform, and are 
              free to choose their preferred hosting.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={zen} width={100} height={100} alt=""/>
              
              <h3 className="text-lg font-medium pt-8 pb-2">
                Minimal and Efficent.
              </h3>
              <p>What could be more aesthetic than utility?</p>
              <h4 className="py-4 text-teal-600">Design tools I use:</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={icon} width={100} height={100} alt="" />
              <Image src={firebaseIcon} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Clean Code.
              </h3>
              <p>Writing quality code that's easy to read.</p>
              <h4 className="py-4 text-teal-600">Using modern tech like:</h4>
              <p className="text-gray-800 py-1">React with Next.js</p>
              <p className="text-gray-800 py-1">GraphQL and ApolloClient</p>
              <p className="text-gray-800 py-1">Sanity, Strapi, Cloudinary, and Firebase.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={payment} width={100} height={100} alt=""/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Start Accepting Secure Payments.
              </h3>
              <p>Free yourself from high transaction fees.</p>
              <h4 className="py-4 text-teal-600">Integrate financial services:</h4>
              <p className="text-gray-800 py-1">Stripe</p>
              <p className="text-gray-800 py-1">Paypal</p>
              <p className="text-gray-800 py-1">Momo</p>
            </div>
          </div>
        </section>
        <section>
          <div className="p-10 leading-8">
          
            <h3 className="text-3xl py-1 mt-20 dark:text-white">Portfolio:</h3>
          </div>
          <div className="p-10 leading-8">
            
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              There are two types of people in the world: problem makers and problem solvers.
              As an entirely self-taught developer, I seek to be the latter. 
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
             Let me find a solution for you, whether that's simply a great landing page for your 
             business, an ecommerce platform for your company, or a media app where you can teach 
             your masterclass. I'm a Zoom call away. I'm a real person who wants to see your business
             succeed. Let's do this.
            </p>

            <h3 className="text-3xl py-1 mt-20 dark:text-white">
              Click on an image to take a peek.
            </h3>
          </div>

          <div className="flex-1 rounded-lg shadow-lg max-h-[20%]">
             <a href="https://programmingwithlevi-uniswap-clone.netlify.app/" target="_blank" rel="noreferrer">
              <Image
                alt="uniswap"
                className="rounded-lg object-cover cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={UniswapClone}
              />
              </a>
            </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap" rel="noreferrer">
           

          
          <div className="basis-1/3 flex-1 rounded-lg shadow-lg">
             <a href="https://programmingwithlevi.github.io/react-player/" target="_blank" rel="noreferrer">
              <Image
                alt="music"
                className="rounded-lg object-cover cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={ReactPlayer}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1 rounded-lg shadow-lg">
             <a href="https://programmingwithlevi-youtube-clone.netlify.app/" target="_blank" rel="noreferrer">
              <Image
                alt="video"
                className="rounded-lg object-cover cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={VideoApp}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1 rounded-lg shadow-lg" >
              <a href="https://store-five-lake.vercel.app/" target="_blank" rel="noreferrer">
              <Image
                alt="store"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Phanox}
              />
              </a> 
            </div>
           
            <div className="basis-1/3 flex-1 rounded-lg shadow-lg">
             <a href="https://realestate-d15r6zbx1-programmingwithlevi.vercel.app/" target="_blank" rel="noreferrer">
              <Image
                alt="realestate"
                className="rounded-lg object-cover cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Realtor}
              />
              </a>
            </div>
            
       
          </div>
        </section>
       
      </main>
    </div>
  );
}
